### PR TITLE
Add Python 3.11 support

### PR DESCRIPTION
**Pull request by gruebel**
pretty straight forward, no issues and deprecation warnings

### CODE REVIEW

**Comment by nicoddemus** [comment]
Strange:

image

Doesn't seem related to the PR, will take a look later.

**Comment by gruebel** [comment]
@nicoddemus I think it was my mistake, I g=somehow forgot to add the Python version `3.11-dev` also to the `python` list in the matrix 🙈

**Comment by nicoddemus** [comment]
Ahh right! Did not catch that because the error was mentioning `runs-on` and ` ${{ matrix.os }}`. 🤦‍♂️

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
