### PR TITLE
Mimic pytest's `project_urls` configuration

### LINKED ISSUE #330: Feature request: Add Documentation link to config for pypi
[Project page on pypi](https://pypi.org/project/pytest-mock/) doesn't have "Documentation" section on the side panel as, e.g. [Django](https://pypi.org/project/Django/) does.

UX can be improved a bit by adding corresponding configuration, similar to [what Django does](https://github.com/django/django/blob/c0a93d39411004300dfda2deb3dc093b69ac6368/setup.cfg#L29-L30)

### PR DESCRIPTION
**Pull request by koutoftimer**
Adds Documentation, Changelog, Source and Tracker urls.

Closes #330

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @koutoftimer!

**Comment by koutoftimer** [comment]
@nicoddemus why? Are you spending time on educating other people to reduce potential amount of work for yourself in the future? Just curious.

**Comment by nicoddemus** [comment]
> @nicoddemus why? Are you spending time on educating other people to reduce potential amount of work for yourself in the future? Just curious.

Sorry, why what?

**Comment by koutoftimer** [comment]
At first you have asked me to contribute, but provided almost exact patch I had to make, also, probably, spent more time in overall to close related issue. In my opinion the only beneficiary in this situation is me, because I've learned something new.

Then you respond with "Thanks @koutoftimer!"

That is why I'm wondering what was your motivation for both actions?

@nicoddemus not sure, maybe I never seen SO polite people.

**Comment by nicoddemus** [comment]
Ahh I see hehehe thanks.

Yeah, in general I tend to guide people in making contributions themselves, even if it takes me more time to do the guidance than doing the contribution myself. It is important to get people involved. 👍

**Pull request merged**
