### PR TITLE
Add assert_has_calls_wrapper

### PR DESCRIPTION
**Pull request by Astral1020**
For this issue [#234](https://github.com/pytest-dev/pytest-mock/issues/234)

image

### CODE REVIEW

**Comment by Astral1020** [comment]
@nicoddemus Do you have time to take a look?

**Comment by nicoddemus** [comment]
Hi @Astral1020,

Yes, thanks a lot for the contribution!

I did take a glance at the implementation, will take a better look later today. Meanwhile, could you add one or more tests to cover the new function? Thanks!

**Comment by acovaci** [comment]
Added unit tests in #365, couldn't figure out how to commit to this :((

**Comment by nicoddemus** [comment]
Superseded by #365, thanks @Astral1020!

**Comment by Astral1020** [comment]
@nicoddemus Sorry I miss the notification, and thank you for keep my commit.

**Comment by nicoddemus** [comment]
Sure thing, thanks again.

**Pull request closed without merging**
