### PR TITLE
Raise an error if mocker is used in a `with` context

### PR DESCRIPTION
**Pull request by binarymason**
Ref: #164

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks a lot @binarymason!

1.11.2 released with this. 👍

**Comment by svanburen** [comment]
fwiw, the CHANGELOG / release notes say `TypeError` while it looks like this actually raises a `ValueError`.

Also, I feel like this should probably catch situations in which multiple context managers are used?

```py
with context_manager_1, mocker.patch(...):
```

Thoughts? Might be harder to detect.

**Comment by nicoddemus** [comment]
> fwiw, the CHANGELOG / release notes say TypeError while it looks like this actually raises a ValueError.

Oh right, I will update the CHANGELOG thanks

> Thoughts? Might be harder to detect.

I thought about that too, but I couldn't come up with a good way to detect that too. In the end though I think this is fine, this will probably catch 99% of the mistakes. 👍 

Thanks again!

**Comment by liamdawson** [comment]
Feedback: whilst presumably for a good reason, this did introduce a breaking change for a rarely-built project of ours.

**Comment by nicoddemus** [comment]
Thanks @liamdawson, can you share more details? This error was introduced because otherwise you would get a criptic message otherwise.

**Pull request merged**
