### PR TITLE
Drop support for EOL Python 3.4

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

It's also little used. Here's the pip installs for pytest-mock from PyPI for September 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  34.03% |   385,722 |
| 3.7      |  31.59% |   358,153 |
| 2.7      |  23.82% |   270,024 |
| 3.5      |   8.69% |    98,545 |
| null     |   0.80% |     9,038 |
| 3.4      |   0.78% |     8,789 |
| 3.8      |   0.24% |     2,747 |
| 2.6      |   0.05% |       607 |
| 3.3      |   0.00% |        15 |
| 3.2      |   0.00% |         1 |
| 3.9      |   0.00% |         1 |
| Total    |         | 1,133,642 |

Date range: 2019-09-01 - 2019-09-30

Source: `pip install -U pypistats && pypistats python_minor pytest-mock --last-month`

Python 3.4 has already been removed from the CI when switching to GitHub actions.

This also updates pre-commit.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @hugovk,

Thanks once again for a PR dropping Python. 😁 

I will hold into this a bit, I'm considering dropping py27 and py35 soon too, might as well do them all together. 👍

**Comment by The-Compiler** [comment]
Not sure if dropping 3.5 already is a good idea - it's [still supported](https://devguide.python.org/#status-of-python-branches) for almost a year. Looking at usage stats:

```
$ pypistats python_minor pytest-mock
| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  38.30% | 2,308,888 |
| 3.7      |  27.43% | 1,653,651 |
| 2.7      |  22.68% | 1,367,364 |
| 3.5      |   9.57% |   577,205 |
| 3.4      |   1.10% |    66,302 |
[...]
```

That being said, I definitely understand the desire to drop it, I'd really like to use f-strings with qutebrowser as well...

**Comment by nicoddemus** [comment]
@The-Compiler oh thanks. For some reason I was under the impression that 3.5 would reach EOL this year, guess I was mistaken. 👍

**Comment by hugovk** [comment]
Any thoughts on how long to keep 2.7 for?

**Comment by nicoddemus** [comment]
It's not being a maintenance problem so far, so I plan to keep it until 2020 comes around. 😁

**Comment by hugovk** [comment]
Please see PR https://github.com/pytest-dev/pytest-mock/pull/176 that includes this one and also drops 2.7.

**Comment by nicoddemus** [comment]
Closing in favor of #176, thanks @hugovk!

**Pull request closed without merging**
